In [4]:
import numpy as np

#criando arrays para testar implementações
train = np.random.rand(5,3) #cinco exemplo de treino, cada exemplo de treino é um array com 3 elementos
test = np.random.rand(2,3) #três exemplos de teste

num_test = test.shape[0]
num_train = train.shape[0]

print("Treino (" + str(num_train) + " elementos):")
print(train)

print("\nTeste (" + str(num_test) + " elementos):")
print(test)

Treino (5 elementos):
[[1.48281146e-04 6.17357088e-01 6.18598747e-01]
 [5.30575307e-01 3.98774750e-01 7.25205259e-01]
 [7.70107957e-01 6.11849439e-01 9.97080119e-01]
 [7.96286209e-01 9.45307629e-01 9.68457931e-01]
 [3.02385317e-02 9.86059129e-01 9.59984277e-01]]

Teste (2 elementos):
[[0.3195795  0.94206522 0.04443515]
 [0.01890658 0.74697593 0.26012425]]


In [5]:
#distancia em dois loops
dists2 = np.zeros((num_test, num_train)) #essa é a matriz das distâncias

#calculando a distancia entre o ith elemento de treino e o jth de teste
i = 0 #máximo de num_train
j = 0 #máximo de num_test
dists2[i][j] = np.sqrt(np.sum((train[i] - test[j])**2))

#aqui é necessário dois laços for para iterar as variáveis i e j
print("dists2=")
print(dists2)

dists2=
[[0.73289529 0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]


In [6]:
#distância em um loop
dists1 = np.zeros((num_test, num_train))

#train[i, :] retorna o ith elemento do conjunto de treinamento

#calcula todas as distâncias para o ith elemento de teste
i = 0

print("ith elemento de teste:")
print(test[i, :])

print("\n(ith elemento de teste - elementos de treino)**2")
print((test[0, :] - train)**2)

print("\nsoma da matriz anterior no axis")
print(np.sum((test[0, :] - train)**2))

print("\nsoma da matriz anterior axis=0")
print(np.sum((test[0, :] - train)**2, axis=0))

print("\nsoma da matriz anterior axis=1")
print(np.sum((test[0, :] - train)**2, axis=1))

print("\nextraindo a raiz quadrada do vetor anterior tem-se a distância do ith elemento de treino para todos os elementos de teste")
dists1[i, :] = np.sqrt(np.sum((test[0, :] - train)**2, axis=1))

print("dists1=")
print(dists1)

ith elemento de teste:
[0.3195795  0.94206522 0.04443515]

(ith elemento de teste - elementos de treino)**2
[[1.02036304e-01 1.05435371e-01 3.29663831e-01]
 [4.45192306e-02 2.95164535e-01 4.63447935e-01]
 [2.02975890e-01 1.09042462e-01 9.07532429e-01]
 [2.27249286e-01 1.05132166e-05 8.53818092e-01]
 [8.37181960e-02 1.93546403e-03 8.38230196e-01]]

soma da matriz anterior no axis
4.564779733796801

soma da matriz anterior axis=0
[0.66049891 0.51158835 3.39269248]

soma da matriz anterior axis=1
[0.53713551 0.8031317  1.21955078 1.08107789 0.92388386]

extraindo a raiz quadrada do vetor anterior tem-se a distância do ith elemento de treino para todos os elementos de teste
dists1=
[[0.73289529 0.89617615 1.10433273 1.03974896 0.96118877]
 [0.         0.         0.         0.         0.        ]]


In [7]:
#distância sem loops
dists0 = np.zeros((num_test, num_train))

#dists0 = raiz(||x²-y²||) = raiz(||x²||-2||x||.||y||+||y²||)

test_norm = np.sum(test**2, axis=1, keepdims=True) #o keepdims=True faz com que o resultado seja uma matriz e não um vetor
print("test_norm")
print(test_norm)

train_norm = np.sum(train**2, axis=1)
print("\ntrain_norm")
print(train_norm)

print("\ntest_norm + train_norm")
print(test_norm + train_norm)

cross = -2.0 * test.dot(train.T)
print("\ncross=")
print(cross)


dists = np.sqrt(test_norm + cross + train_norm)
print("\ndists=")
print(dists)

test_norm
[[0.99159242]
 [0.62599512]]

train_norm
[0.76379421 0.96645413 1.96159477 2.465589   1.89479679]

test_norm + train_norm
[[1.75538663 1.95804655 2.95318719 3.45718142 2.88638921]
 [1.38978932 1.59244924 2.58758988 3.09158412 2.5207919 ]]

cross=
[[-1.21825112 -1.15491484 -1.7336364  -2.37610353 -1.96250535]
 [-1.24413244 -0.99309995 -1.46192324 -1.94619296 -1.97369865]]

dists=
[[0.73289529 0.89617615 1.10433273 1.03974896 0.96118877]
 [0.38165021 0.77417653 1.06097438 1.07022949 0.73965752]]


In [8]:
#testando cross-validation
x_train = np.random.rand(20,3) #20 exemplos de teste
y_train = np.random.rand(20) #20 exemplos de teste

"""
for i in range(20):
    x_train[i].append(i)
    y_train[i].append(i)
"""
print(x_train)
print(y_train)


[[0.98246564 0.11182521 0.53210391]
 [0.31704657 0.08390034 0.65211371]
 [0.21432308 0.23764602 0.19049648]
 [0.42257638 0.95496834 0.96823037]
 [0.728053   0.20462248 0.25458326]
 [0.5223966  0.83235881 0.45208951]
 [0.04764714 0.99827998 0.60671415]
 [0.07246229 0.8041709  0.47058733]
 [0.85572134 0.95776827 0.71998363]
 [0.78582436 0.40254612 0.47805441]
 [0.05402804 0.36408646 0.51854852]
 [0.08937241 0.17170089 0.17044934]
 [0.99229467 0.14566731 0.29978376]
 [0.15513762 0.51809986 0.26877802]
 [0.44739312 0.81430951 0.36959541]
 [0.16269067 0.25208725 0.26588436]
 [0.39956329 0.75766641 0.25832335]
 [0.19104598 0.40372066 0.12540261]
 [0.22611785 0.16241953 0.03373756]
 [0.30052485 0.80885879 0.32259892]]
[0.4117224  0.36610082 0.07400145 0.11187499 0.26802778 0.85612827
 0.19092331 0.54830331 0.82799893 0.46206287 0.35788468 0.44834171
 0.36721218 0.08503694 0.91165556 0.19081163 0.80618526 0.05655644
 0.66212454 0.29766142]


In [9]:
x_train_folds = np.split(x_train, 4)
y_train_folds = np.split(y_train, 4)

print(x_train_folds)
print(y_train_folds)

[array([[0.98246564, 0.11182521, 0.53210391],
       [0.31704657, 0.08390034, 0.65211371],
       [0.21432308, 0.23764602, 0.19049648],
       [0.42257638, 0.95496834, 0.96823037],
       [0.728053  , 0.20462248, 0.25458326]]), array([[0.5223966 , 0.83235881, 0.45208951],
       [0.04764714, 0.99827998, 0.60671415],
       [0.07246229, 0.8041709 , 0.47058733],
       [0.85572134, 0.95776827, 0.71998363],
       [0.78582436, 0.40254612, 0.47805441]]), array([[0.05402804, 0.36408646, 0.51854852],
       [0.08937241, 0.17170089, 0.17044934],
       [0.99229467, 0.14566731, 0.29978376],
       [0.15513762, 0.51809986, 0.26877802],
       [0.44739312, 0.81430951, 0.36959541]]), array([[0.16269067, 0.25208725, 0.26588436],
       [0.39956329, 0.75766641, 0.25832335],
       [0.19104598, 0.40372066, 0.12540261],
       [0.22611785, 0.16241953, 0.03373756],
       [0.30052485, 0.80885879, 0.32259892]])]
[array([0.4117224 , 0.36610082, 0.07400145, 0.11187499, 0.26802778]), array([0.85612827, 0.

In [10]:
i = 1 #fold para validação

x_train_set = x_train_folds[:i] + x_train_folds[i+1:]

print(x_train_set)

x_train_set = np.vstack(x_train_folds[:i] + x_train_folds[i+1:])

print(x_train_set)

[array([[0.98246564, 0.11182521, 0.53210391],
       [0.31704657, 0.08390034, 0.65211371],
       [0.21432308, 0.23764602, 0.19049648],
       [0.42257638, 0.95496834, 0.96823037],
       [0.728053  , 0.20462248, 0.25458326]]), array([[0.05402804, 0.36408646, 0.51854852],
       [0.08937241, 0.17170089, 0.17044934],
       [0.99229467, 0.14566731, 0.29978376],
       [0.15513762, 0.51809986, 0.26877802],
       [0.44739312, 0.81430951, 0.36959541]]), array([[0.16269067, 0.25208725, 0.26588436],
       [0.39956329, 0.75766641, 0.25832335],
       [0.19104598, 0.40372066, 0.12540261],
       [0.22611785, 0.16241953, 0.03373756],
       [0.30052485, 0.80885879, 0.32259892]])]
[[0.98246564 0.11182521 0.53210391]
 [0.31704657 0.08390034 0.65211371]
 [0.21432308 0.23764602 0.19049648]
 [0.42257638 0.95496834 0.96823037]
 [0.728053   0.20462248 0.25458326]
 [0.05402804 0.36408646 0.51854852]
 [0.08937241 0.17170089 0.17044934]
 [0.99229467 0.14566731 0.29978376]
 [0.15513762 0.51809986 0.2687

In [11]:
y_train_set = y_train_folds[:i] + y_train_folds[i+1:]

print(y_train_set)

y_train_set = np.hstack(y_train_folds[:i] + y_train_folds[i+1:])

print(y_train_set)

[array([0.4117224 , 0.36610082, 0.07400145, 0.11187499, 0.26802778]), array([0.35788468, 0.44834171, 0.36721218, 0.08503694, 0.91165556]), array([0.19081163, 0.80618526, 0.05655644, 0.66212454, 0.29766142])]
[0.4117224  0.36610082 0.07400145 0.11187499 0.26802778 0.35788468
 0.44834171 0.36721218 0.08503694 0.91165556 0.19081163 0.80618526
 0.05655644 0.66212454 0.29766142]


In [12]:
x_validation = x_train_folds[i]
y_validation = y_train_folds[i]

print(x_validation)
print(y_validation)

[[0.5223966  0.83235881 0.45208951]
 [0.04764714 0.99827998 0.60671415]
 [0.07246229 0.8041709  0.47058733]
 [0.85572134 0.95776827 0.71998363]
 [0.78582436 0.40254612 0.47805441]]
[0.85612827 0.19092331 0.54830331 0.82799893 0.46206287]


In [25]:
#testando predict label
"""
lembrando:
train = np.random.rand(5,3) #cinco exemplo de treino, cada exemplo de treino é um array com 3 elementos
test = np.random.rand(2,3) #três exemplos de teste

dists é a matriz de distâncias
"""
print(train)
print(test)
print(dists)

y_train2 = np.random.rand(5) #20 exemplos de teste

[[1.48281146e-04 6.17357088e-01 6.18598747e-01]
 [5.30575307e-01 3.98774750e-01 7.25205259e-01]
 [7.70107957e-01 6.11849439e-01 9.97080119e-01]
 [7.96286209e-01 9.45307629e-01 9.68457931e-01]
 [3.02385317e-02 9.86059129e-01 9.59984277e-01]]
[[0.3195795  0.94206522 0.04443515]
 [0.01890658 0.74697593 0.26012425]]
[[0.73289529 0.89617615 1.10433273 1.03974896 0.96118877]
 [0.38165021 0.77417653 1.06097438 1.07022949 0.73965752]]


In [37]:
k = 5
i = 0
closest_n = np.argsort(dists[i])[:k]
print(closest_n)

[0 1 4 3 2]


In [38]:
closest_y = []
closest_y.extend(y_train2[closest_n])

print(closest_y)

[0.17320866697557247, 0.6547594881568608, 0.6571693285568965, 0.5441672853611903, 0.2161103929771312]


In [39]:
closest_y.sort()
print(closest_y)

[0.17320866697557247, 0.2161103929771312, 0.5441672853611903, 0.6547594881568608, 0.6571693285568965]


In [31]:
y_pred = np.zeros(2)
print(y_pred)

[0. 0.]


In [36]:
from scipy import stats
y_pred[i] = stats.mode(closest_y)[0][0]
print(y_pred)

[0.17320867 0.        ]
